export let products = [
  {
    id: 1,
    name: "Remera Eagle Negra",
    category: "remeras",
    imgUrl: "./assets/img/remeraBlessedNegra.png",
    price: 5500,
    stock: 20,
  },
  {
    id: 2,
    name: "Remera Eagle Naranja",
    category: "remeras",
    imgUrl: "./assets/img/remeraBlessedNaranja.png",
    price: 5500,
    stock: 20,
  },
  {
    id: 3,
    name: "Remera Eagle Blanca",
    category: "remeras",
    imgUrl: "./assets/img/remeraBlessedBlanca.png",
    price: 5500,
    stock: 10,
  },
  {
    id: 4,
    name: "Boxers CK x 3",
    category: "ropaInteriorHombre",
    imgUrl: "./assets/img/boxerCK.png",
    price: 5000,
    stock: 10,
  },
  {
    id: 5,
    name: "Boxer Lody",
    category: "ropaInteriorHombre",
    imgUrl: "./assets/img/boxerLody.png",
    price: 2800,
    stock: 10,
  },
  {
    id: 6,
    name: "Boxer Poker",
    category: "ropaInteriorHombre",
    imgUrl: "./assets/img/boxerPoker.png",
    price: 1800,
    stock: 0,
  },
  {
    id: 7,
    name: "Conjunto CK Blanco",
    category: "ropaInteriorMujer",
    imgUrl: "./assets/img/conjuntoCKBlanco.png",
    price: 2800,
    stock: 20,
  },
  {
    id: 8,
    name: "Conjunto CK Gris",
    category: "ropaInteriorMujer",
    imgUrl: "./assets/img/conjuntoCKGris.png",
    price: 2800,
    stock: 20,
  },
  {
    id: 9,
    name: "Conjunto CK Rojo",
    category: "ropaInteriorMujer",
    imgUrl: "./assets/img/conjuntoCKRojo.png",
    price: 2800,
    stock: 0,
  },
  {
    id: 10,
    name: "Conjunto Frida",
    category: "ropaInteriorMujer",
    imgUrl: "./assets/img/conjuntoFrida.png",
    price: 2900,
    stock: 20,
  },
  {
    id: 11,
    name: "Medias Alien",
    category: "medias",
    imgUrl: "./assets/img/mediasAlien.png",
    price: 1000,
    stock: 0,
  },
  {
    id: 12,
    name: "Medias Animales x 3",
    category: "medias",
    imgUrl: "./assets/img/mediasAnimales.png",
    price: 2800,
    stock: 5,
  },
  {
    id: 13,
    name: "Medias Game Over",
    category: "medias",
    imgUrl: "./assets/img/mediasGameOver.jpg",
    price: 1000,
    stock: 5,
  },
  {
    id: 14,
    name: "Medias Peach",
    category: "medias",
    imgUrl: "./assets/img/mediasPeach.png",
    price: 1000,
    stock: 5,
  },
  {
    id: 15,
    name: "Medias Sushi",
    category: "medias",
    imgUrl: "./assets/img/mediasSushi.png",
    price: 1000,
    stock: 5,
  },
];
